### ISSUE TITLE
Implementing privacy modes

### ISSUE THREAD

**Issue by cryptix** [ssb-ngi-pointer/go-ssb-room#96]
# Documentation
https://ssb-ngi-pointer.github.io/rooms2/#stakeholders
https://ssb-ngi-pointer.github.io/rooms2/#privacy-modes
https://ssb-ngi-pointer.github.io/rooms2/#participation

background:
https://github.com/ssb-ngi-pointer/go-ssb-room/issues/12

## implementation implications

The room server needs to support the three modes (open, community, restricted).

Areas where privacy mode needs to be considered:
* invites
* connection establishment
* Aliases: restricted rooms don't support aliases, because restricted means to be completely shut off from the public
* more?

## remaining
the following tasks are what remains. they may be implemented in #100 or in a separate follow-up pr

* [x] clean up thinking-out-loud comments
* [x] figure out which tests are low-hanging fruit for the privacy modes logic in #100
  * [x] write those tests
* [x] final review of #100, catching any last mistakes/bugs
* [x] go through rebase hell
* [x] in pr #126: implement setting the privacy mode from the dashboard / http frontend views
* [x] in pr #122: add deny list logic to the invites parts (yes?)
* [x] in pr #137: migrate privacy modes ui to a separate settings view (related to #134)
* [x] in pr #139: add test for deny list application on connection establishment, in `muxrpc/test/go`
* [x] in  pr #179: disable ui if privacy mode does not allow for actions (e.g. invites)
* [ ] in the other pr: write more tests 
  * [ ] verifying restricted mode behaviour
  * [ ] verifying community mode behaviour
  * [ ] verifying open mode behaviour
  * [ ] tests for changing the privacy mode over POST requests?
 
## ideas

First round: start server with a command line flag for the target privacy mode, expose in the interface what the current privacy mode is

:ballot_box_with_check:  add `type RoomConfig interface { ... }` to package roomdb but do not implement it in sqlite in the first pass of things.

 * to interface.go ( https://github.com/ssb-ngi-pointer/go-ssb-room/blob/master/roomdb/interface.go )

```go
type RoomConfig interface {
    GetPrivacyMode(context.Context) (PrivacyMode, error)
}
```

where `type PrivacyMode` similar to roomdb.RoleMember enum etc

* then implement RoomConfig interface in cmd/server
* then you can pass it into all the web/handlers.New(...) init code
    * https://github.com/ssb-ngi-pointer/go-ssb-room/blob/07feacb5587e2baa912b8203909cf41fa6f0a672/cmd/server/main.go#L247
    * https://github.com/ssb-ngi-pointer/go-ssb-room/blob/07feacb5587e2baa912b8203909cf41fa6f0a672/web/handlers/http.go#L72
    * https://github.com/ssb-ngi-pointer/go-ssb-room/blob/07feacb5587e2baa912b8203909cf41fa6f0a672/web/handlers/http.go#L46
* later we can remove it and replace with roomdb/sqlite and start adding SetMode(...) to RoomConfig

### What actions are regulated by the privacy mode, and where?
* invite creation
    https://github.com/ssb-ngi-pointer/go-ssb-room/blob/07feacb5587e2baa912b8203909cf41fa6f0a672/web/handlers/admin/invites.go#L47
* who can connect to the room 
    https://github.com/ssb-ngi-pointer/go-ssb-room/blob/07feacb5587e2baa912b8203909cf41fa6f0a672/roomsrv/init_network.go#L30
    * add deny list around line 30
* who can see the connected members (ie tunnel.endpoints)
    https://github.com/ssb-ngi-pointer/go-ssb-room/blob/07feacb5587e2baa912b8203909cf41fa6f0a672/muxrpc/handlers/tunnel/server/state.go#L60

how to get the role of a member:
    https://github.com/ssb-ngi-pointer/go-ssb-room/blob/07feacb5587e2baa912b8203909cf41fa6f0a672/web/handlers/admin/members.go#L81-L86

## later (persistence)

* Add a `SetPrivacyMode(ctx, mode) error` to the `RoomConfig` interface
* Add a new table by creating a new file in `sqlite/migrations` (probably 3-room-config.sql)
    (the increasing numbers are just a convention to understand the order better)
* Run `bash ./generate-models.sh` in `roomdb/sqlite` to update the `models` package
* Start using the generated model of the new table to implement `RoomConfig`

## and of course:
    TESTS!!

**Comment by staltz** [comment]
> implementation implications

Restricted rooms don't support aliases, because they're meant to be completely shut off from the public.

**Comment by cryptix** [comment]
Right, thanks! Update the outline above.

**Comment by cryptix** [comment]
Reopening since this is a tracking issue for _all_ the features.

Notable PR #100 is missing UI for changing the modes and lots of tests to make sure they work as intended across all the features.
